class CountryData:
    lang_initials_dict = {
        'Afghanistan': ('af_AF',),
        'Albania': ('sq_AL',),
        'Algeria': ('ar_DZ',),
        'Andorra': ('ca_AD',),
        'Angola': ('pt_AO',),
        'Antigua and Barbuda': ('en_AG',),
        'Argentina': ('es_AR',),
        'Armenia': ('hy_AM',),
        'Australia': ('en_AU',),
        'Austria': ('de_AT',),
        'Azerbaijan': ('az_AZ',),
        'Bahamas': ('en_BS',),
        'Bahrain': ('ar_BH',),
        'Bangladesh': ('bn_BD',),
        'Barbados': ('en_BB',),
        'Belarus': ('be_BY',),
        'Belgium': ('fr_BE', 'nl_BE'),
        'Belize': ('en_BZ',),
        'Benin': ('fr_BJ',),
        'Bhutan': ('dz_BT',),
        'Bolivia': ('es_BO',),
        'Bosnia and Herzegovina': ('bs_BA',),
        'Botswana': ('en_BW',),
        'Brazil': ('pt_BR',),
        'Brunei Darussalam': ('ms_BN',),
        'Bulgaria': ('bg_BG',),
        'Burkina Faso': ('fr_BF',),
        'Burundi': ('rn_BI',),
        'Cambodia': ('km_KH',),
        'Cameroon': ('fr_CM',),
        'Canada': ('es_CA', 'fr_CA'),
        'Cape Verde': ('pt_CV',),
        'Central African Republic': ('fr_CF',),
        'Chad': ('fr_TD',),
        'Chile': ('es_CL',),
        'China': ('zh_CN',),
        'Colombia': ('es_CO',),
        'Comoros': ('ar_KM',),
        'Costa Rica': ('es_CR',),
        'Croatia': ('hr_HR',),
        'Cuba': ('es_CU',),
        'Cyprus': ('el_CY',),
        'Czech Republic': ('cs_CZ',),
        "Côte d'Ivoire": ('fr_CI',),
        'Democratic Republic of the Congo': ('fr_CD',),
        'Denmark': ('da_DK',),
        'Djibouti': ('fr_DJ',),
        'Dominica': ('en_DM',),
        'Dominican Republic': ('es_DO',),
        'East Timor': ('pt_TL',),
        'Ecuador': ('es_EC',),
        'Egypt': ('ar_EG',),
        'El Salvador': ('es_SV',),
        'Equatorial Guinea': ('es_GQ',),
        'Eritrea': ('ti_ER',),
        'Estonia': ('et_EE',),
        'Ethiopia': ('am_ET',),
        'Federated States of Micronesia': ('en_FM',),
        'Fiji': ('en_FJ',),
        'Finland': ('fi_FI',),
        'France': ('fr_FR',),
        'Gabon': ('fr_GA',),
        'Georgia': ('ka_GE',),
        'Germany': ('de_DE',),
        'Ghana': ('tw_GH',),
        'Greece': ('el_GR',),
        'Grenada': ('en_GD',),
        'Guatemala': ('es_GT',),
        'Guinea': ('fr_GN',),
        'Guinea-Bissau': ('pt_GW',),
        'Guyana': ('en_GY',),
        'Haiti': ('fr_HT',),
        'Honduras': ('es_HN',),
        'Hungary': ('hu_HU',),
        'Iceland': ('is_IS',),
        'India': ('en_IN', 'hi_IN', 'ta_IN', 'or_IN'),
        'Indonesia': ('id_ID',),
        'Iran': ('fa_IR',),
        'Iraq': ('ar_IQ',),
        'Ireland': ('en_IE', 'ga_IE'),
        'Israel': ('he_IL',),
        'Italy': ('it_IT',),
        'Jamaica': ('en_JM',),
        'Japan': ('ja_JP',),
        'Jordan': ('ar_JO',),
        'Kazakhstan': ('kk_KZ',),
        'Kenya': ('sw_KE',),
        'Kingdom of the Netherlands': ('nl_NL',),
        'Kiribati': ('en_KI',),
        'Kuwait': ('ar_KW',),
        'Kyrgyzstan': ('ky_KG',),
        'Laos': ('lo_LA',),
        'Latvia': ('lv_LV',),
        'Lebanon': ('ar_LB',),
        'Lesotho': ('en_LS',),
        'Liberia': ('en_LR',),
        'Libya': ('ar_LY',),
        'Liechtenstein': ('de_LI',),
        'Lithuania': ('lt_LT',),
        'Luxembourg': ('fr_LU', 'de_LU'),
        'Madagascar': ('mg_MG',),
        'Malawi': ('en_MW',),
        'Malaysia': ('ms_MY',),
        'Maldives': ('dv_MV',),
        'Mali': ('fr_ML',),
        'Malta': ('mt_MT',),
        'Marshall Islands': ('en_MH',),
        'Mauritania': ('ar_MR',),
        'Mauritius': ('en_MU',),
        'Mexico': ('es_MX',),
        'Moldova': ('ro_MD',),
        'Monaco': ('fr_MC',),
        'Mongolia': ('mn_MN',),
        'Montenegro': ('sr_ME',),
        'Morocco': ('ar_MA',),
        'Mozambique': ('pt_MZ',),
        'Myanmar': ('my_MM',),
        'Namibia': ('en_NA',),
        'Nauru': ('en_NR',),
        'Nepal': ('ne_NP',),
        'New Zealand': ('en_NZ',),
        'Nicaragua': ('es_NI',),
        'Niger': ('fr_NE',),
        'Nigeria': ('en_NG',),
        'North Korea': ('ko_KP',),
        'North Macedonia': ('mk_MK',),
        'Norway': ('no_NO',),
        'Oman': ('ar_OM',),
        'Pakistan': ('ur_PK',),
        'Palau': ('en_PW',),
        'Palestine': ('ar_PS',),
        'Panama': ('es_PA',),
        'Papua New Guinea': ('en_PG',),
        'Paraguay': ('es_PY',),
        "People's Republic of China": ('zh_CN',),
        'Peru': ('es_PE',),
        'Philippines': ('en_PH',),
        'Poland': ('pl_PL',),
        'Portugal': ('pt_PT',),
        'Qatar': ('ar_QA',),
        'Republic of Ireland': ('en_IE', 'ga_IE'),
        'Republic of the Congo': ('fr_CG',),
        'Romania': ('ro_RO',),
        'Russia': ('ru_RU',),
        'Rwanda': ('rw_RW',),
        'Saint Kitts and Nevis': ('en_KN',),
        'Saint Lucia': ('en_LC',),
        'Saint Vincent and the Grenadines': ('en_VC',),
        'Samoa': ('sm_WS',),
        'San Marino': ('it_SM',),
        'Saudi Arabia': ('ar_SA',),
        'Senegal': ('fr_SN',),
        'Serbia': ('sr_RS',),
        'Seychelles': ('fr_SC',),
        'Sierra Leone': ('en_SL',),
        'Singapore': ('en_SG',),
        'Slovakia': ('sk_SK',),
        'Slovenia': ('sl_SI',),
        'Solomon Islands': ('en_SB',),
        'Somalia': ('so_SO',),
        'South Africa': ('zu_ZA',),
        'South Korea': ('ko_KR',),
        'Spain': ('es_ES',),
        'Sri Lanka': ('si_LK',),
        'Sudan': ('ar_SD',),
        'Suriname': ('nl_SR',),
        'Swaziland': ('en_SZ',),
        'Sweden': ('sv_SE',),
        'Switzerland': ('de_CH', 'fr_CH'),
        'Syria': ('ar_SY',),
        'São Tomé and Príncipe': ('pt_ST',),
        'Taiwan': ('zh_TW',),
        'Tajikistan': ('tg_TJ',),
        'Tanzania': ('sw_TZ',),
        'Thailand': ('en_TH',),
        'The Gambia': ('en_GM',),
        'Togo': ('fr_TG',),
        'Tonga': ('en_TO',),
        'Trinidad and Tobago': ('en_TT',),
        'Tunisia': ('ar_TN',),
        'Turkey': ('tr_TR',),
        'Turkmenistan': ('tk_TM',),
        'Tuvalu': ('en_TV',),
        'Uganda': ('sw_UG',),
        'Ukraine': ('uk_UA', 'uk_UK'),
        'United Arab Emirates': ('ar_AA',),
        'United Kingdom': ('en_GB',),
        'United States': ('en_US',),
        'Uruguay': ('es_UY',),
        'Uzbekistan': ('uz_UZ',),
        'Vanuatu': ('bi_VU',),
        'Vatican City': ('it_VA',),
        'Venezuela': ('es_VE',),
        'Vietnam': ('vi_VN',),
        'Yemen': ('ar_YE',),
        'Zambia': ('en_ZM',),
        'Zimbabwe': ('en_ZW',)
    }



